/* Constants */
newsModule.constant( 'NEWST', {
	NEWS_TYPE_REGULAR : 0,
	NEWS_TYPE_NOLEAD  : 1,
	NEWS_TYPE_COMPACT : 2,
	NEWS_BASE_COUNT   : 20,
	NEWS_SCROLL_COUNT : 20,

	AUTOCOMPLETE_BASE_COUNT : 6,

	FEED_TYPE_COMMON : 0,
	FEED_TYPE_USER   : 1,
	FEED_TYPE_FAV    : 2,

	FEED_GROUPTYPE_COMMON : 'feed',
	FEED_GROUPTYPE_USER   : 'user-feed',
	FEED_GROUPTYPE_FAV    : 'favorite',

	FEED_COMMON_ID     : 'common',
	FEED_COMMONUSER_ID : 'common-user',

	OBJECT_TYPE_RUBRIC : 'hier_rubric',
	OBJECT_TYPE_TAG    : 'tag',

	PRIORITY_MOSTURGENT : 1,
	PRIORITY_URGENT     : 2,

	MAX_FEED_MESSAGES_TO_SUBSCRIBE : 12
});